# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170715_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='date_publish',
        ),
    ]
