# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_iplist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplist',
            name='time',
            field=models.TimeField(default=1509628152.9413836),
        ),
    ]
