# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171102_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplist',
            name='time',
            field=models.TimeField(default=1509628244.5446231),
        ),
    ]
