# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171102_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iplist',
            options={'verbose_name': '访问时间', 'verbose_name_plural': '访问时间'},
        ),
        migrations.AlterField(
            model_name='iplist',
            name='time',
            field=models.TimeField(default=1509628332.8736753),
        ),
    ]
