# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20171102_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('time', models.TimeField(default=1509628417.2685025)),
            ],
            options={
                'verbose_name': '访问时间',
                'verbose_name_plural': '访问时间',
            },
        ),
        migrations.DeleteModel(
            name='Iplist',
        ),
    ]
