# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20171102_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
