# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 23:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20171102_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='login_sta',
            field=models.CharField(default=0, max_length=2, verbose_name='登录是否锁定'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_suo',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 23, 12, 27, 516329), verbose_name='登录锁定时间'),
        ),
    ]
