# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20171102_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_suo',
            field=models.DateTimeField(verbose_name='登录锁定时间'),
        ),
    ]
