# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20171104_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pass_errnum',
            field=models.IntegerField(default=0, verbose_name='用户密码输入次数'),
        ),
    ]
