# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20171106_1038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pass_errnum',
        ),
    ]
